### ISSUE TITLE
Somali orthography

### ISSUE THREAD

**Issue by inariksit** [GrammaticalFramework/gf-wordnet#28]
Great to have Somali coverage in GF! 

I'm curious to know where the data is from. It looks rather linguistic, with lots of IPA characters. 

```haskell
lin question_1_V2 = mkV2 (mkV "suʔal") noPrep ; --guessed
lin put_6_V2 = mkV2 (mkV "ɖɪg") noPrep ; --guessed
lin squeeze_1_V2 = mkV2 (mkV "tuːǯi") noPrep ; --guessed
```

The sources I've read that try to adhere to Somali conventions (like [this one](http://morgannilsson.se/BeginnersSomaliGrammar.pdf)), would use `'` for the glottal stop, and `dh` for the retroflex. The word *squeeze* would be written `tuuji`. There are many other examples as well, and I'm not quite sure about all of them. So I'd like to know the source, so I can make a more educated guess.

I would like the GF resource to reflect more the prevalent usage than grammar books. If you agree, I can take care of the transliteration.

### Smart paradigms for verbs

This is a TODO item for myself.

When I wrote the fragments of the Somali RG 2 years ago, I left my verb morphology quite unfinished. I was trying to decide which form would be the dictionary form, and found different conventions in different lexica and grammars. I didn't come to a conclusion, so my current implementation takes an artificial stem, which is not any actual wordform. I can adjust my smart paradigms to work with different forms, but that's good to keep in mind if we get words from different sources: their dictionary form may not be the same.

**Comment by krangelov** [comment]
Afrikans, Maltese, Romanian, Somali and Swahili are new additions which are
just proof of concept to show that new languages can be added even without
any existing WordNet. Basically I search for translations in PanLex from
all existing languages to the target language. After that I use different
features to decide which one is the best translation.

For the morphology I imported external sources when I can find one or I
used the smart paradigms if the word cannot be found otherwise. None of the
above languages have an existing morphological lexicon but for instance for
German and French there were.

PanLex contains thousands of bilingual lexicons in hundreds of languages
and they all come from different sources. In particular for Somali, I
listed the used sources below. Feel free to make any adjustments necessary.
I can also easily regenerate the dictionary if you find that something in
general is wrong.


CLDR Version 6.1, By-Type Chart: names.language
Unicode Common Locale Data Repository
Languages in their original form
Geonames: Language codes
PanLex meta-source
List of ISO 639-3 codes
Dbnary: Wiktionary as Linguistic Linked Open Data
Wiktionary
Wikiwörterbuch
Wîkîferheng
Wiktionary tiếng Việt
Wikisanakirja
Wiktionnaire
Lexicon Enhancement via the GOLD Ontology Wordlists
The ASJP Database
Reading in Somali: An Elementary Cultural Reader
Geonames: Glossaries
Wikiorðabók
HeiNER - the Heidelberg Named Entity Resource
Continents
Unicode Common Locale Data Repository — Territories
Wikizionario
The days of the week in various languages
വിക്കിനിഘണ്ടു
Vikisõnastik
International Organizations
Викисловарь
Linked Languages Resources
The months of the Gregorian (Christian) calendar in various languages
Oceans
Astronomia Terminaro
Numbers from 1 to 10 in over 5000 languages
Some Fields of Science
Seas and Straits
Mountains
Solar System
Peace in various languages
The months of other calendars in various languages
Circles of latitude
Some Historical People
Times in History
Some Works of Literature and a Ballet
Football World Cup
The books of the New Testament

**Comment by inariksit** [comment]
Okay, I understand! So it's likely that already the words in there currently have different base forms. Unfortunately I don't know Somali in any meaningful way, just random anecdotes about morphosyntax. :-P But I noticed that the word "ulayn" appears as a translation for 890 different words, which seem to be pretty arbitrary (here's a party game: what's in common with _accept_, _chop_, _paste_, _seduce_, _trash_… and 800+ more words?)

I think I'll contact someone who actually knows Somali, and try to organise a meeting to go through the lexicon. I'll get back to you after I have some more information.
